services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_kobo
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
